all:
    children:
        backend:
            hosts:
                db-machine:
                    ansible_host: 52.67.227.190
                    ansible_user: ubuntu
                    ansible_ssh_private_key_file: ./inventory/webbudget.pem
        frontend:
            hosts:
                web-machine-1:
                    ansible_host: 54.94.119.173
                    ansible_user: ubuntu
                    ansible_ssh_private_key_file: ./inventory/webbudget.pem
                
                web-machine-2:
                    ansible_host: 15.228.39.6
                    ansible_user: ubuntu
                    ansible_ssh_private_key_file: ./inventory/webbudget.pem