---
- name: Instalando aptitude.
  apt:  # Módulo de instalação de pacotes e dependências apt.
    name: aptitude 
    state: latest 
    update_cache: yes 
    force_apt_get: yes 
  become: yes

- name: Instalando pacotes requeridos pelo sistema.
  apt: # Módulo de instalação de pacotes e dependências apt.
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv',
'python3-setuptools', 'docker-compose'] 
    state: latest 
    update_cache: yes 
  become: yes

- name: Instalando chave do repositório do docker.
  apt_key: # Módulo de instalação de chaves de repositorios apt.
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Adicionando repositório docker.
  apt_repository: # Módulo para adição de repositórios apt.
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  become: yes  

- name: Atualizando repositórios e instalando docker-ce
  apt:  # Módulo de instalação de pacotes e dependências apt.
    name: docker-ce 
    state: latest
    update_cache: yes 
  become: yes


- name: Instalando o módulo Docker para Python.
  pip: # Módulo de instalação de pacotes e dependências Python.
    name: docker
  become: yes

- name: Adicionando usuário ao grupo "docker".
  user: # Módulo de configuração de usuário e grupos do linux.
    name: ubuntu
    group: docker
    append: yes
  become: yes